
apiVersion: v1
kind: Pod
metadata:
  name: e2e-tests
spec:
  containers:
  - name: e2e-tests
    image: alpine:latest
    command: 
      - "sh"
      - "-c"
      - "apk add --no-cache curl postgresql-client bash netcat-openbsd iputils && sleep 3600"
    envFrom:
    - secretRef:
        name: e2e-env-secret