
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  POSTGRES_DB: zelda_cookbook
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DATABASE_URL: postgres://postgres:postgres@db:5432/zelda_cookbook
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      include /etc/nginx/mime.types;
      
      # Extended logging settings
      log_format detailed '$remote_addr - $remote_user [$time_local] '
                          '"$request" $status $body_bytes_sent '
                          '"$http_referer" "$http_user_agent" '
                          'request_type="$request_type"';
      
      # Custom variable to identify request type
      map $uri $request_type {
        default "static";
        ~^/api/ "api_proxy";
      }
      
      server {
        listen 80;
        server_name localhost;
        
        # Configure extended logging
        access_log /var/log/nginx/access.log detailed;
        
        location / {
          root /usr/share/nginx/html;
          index index.html index.htm;
          try_files $uri $uri/ /index.html;
          
          # Add headers to mark static files
          add_header X-Content-Source "static-file" always;
          add_header X-Served-By "nginx-static" always;
        }
        
        location /api {
          proxy_pass http://be:3010;
          
          # Add headers to mark API proxy
          add_header X-Content-Source "api-proxy" always;
          add_header X-Served-By "nginx-proxy" always;
          
          # Forward headers to backend server
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        # NGINX status page for monitoring
        location = /nginx_status {
          stub_status on;
          access_log off;
        }
      }
    }


# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: db-config
# data:
#   POSTGRES_DB: zelda_cookbook
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: db-secret
# type: Opaque
# stringData:
#   POSTGRES_USER: postgres
#   POSTGRES_PASSWORD: postgres
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: backend-config
# data:
#   DATABASE_URL: postgres://postgres:postgres@db:5432/zelda_cookbook
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: nginx-config
# data:
#   nginx.conf: |
#     events {}
#     http {
#       include /etc/nginx/mime.types;
#       server {
#         listen 80;
#         server_name localhost;
        
#         location / {
#           root /usr/share/nginx/html;
#           index index.html index.htm;
#           try_files $uri $uri/ /index.html;
#         }
        
#         location /api {
#           proxy_pass http://be:3010;
#         }
#       }
#     }